apiVersion: 1

datasources:
  - name: "Prometheus"
    type: "prometheus"
    access: "proxy"
    url: "http://prometheus:9091"
    isDefault: true
    typeLogoUrl: "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
    editable: true
    jsonData:
      timeInterval: "30s"  # Set the query interval in Grafana